/**
 * Export services to convert transcriptions into plain text TXT, MS Word DOC, or print PDFs.
 */

export function exportToTXT(text) {
  const blob = new Blob([text], { type: "text/plain;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = `transcript_${Date.now()}.txt`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

export function exportToPDF(text) {
  const printWindow = window.open("", "_blank");
  if (!printWindow) return;
  printWindow.document.write(`
    <html>
      <head>
        <title>Hindi Transcript</title>
        <style>
          body { font-family: 'Inter', system-ui, -apple-system, sans-serif; padding: 40px; line-height: 1.85; color: #111827; max-width: 800px; margin: 0 auto; }
          h1 { font-size: 24px; font-weight: 700; border-bottom: 1px solid #e5e7eb; padding-bottom: 12px; margin-bottom: 24px; }
          p { font-size: 16px; white-space: pre-wrap; color: #1f2937; }
          .footer { font-size: 12px; color: #9ca3af; margin-top: 48px; border-top: 1px solid #e5e7eb; padding-top: 12px; }
        </style>
      </head>
      <body>
        <h1>Hindi ASR Transcription Document</h1>
        <p>${text}</p>
        <div class="footer">Generated by Hindi ASR. © 2026.</div>
        <script>
          window.onload = function() {
            window.print();
            setTimeout(function() { window.close(); }, 500);
          };
        </script>
      </body>
    </html>
  `);
  printWindow.document.close();
}

export function exportToDOCX(text) {
  const html = `
    <html xmlns:o='urn:schemas-microsoft-com:office:office' xmlns:w='urn:schemas-microsoft-com:office:word' xmlns='http://www.w3.org/TR/REC-html40'>
      <head>
        <title>ASR Transcript</title>
        <meta charset="utf-8">
        <style>
          body { font-family: Arial, sans-serif; line-height: 1.6; padding: 20px; }
          h2 { font-size: 20px; color: #111827; border-bottom: 1px solid #e5e7eb; padding-bottom: 8px; }
          p { font-size: 14px; color: #1f2937; }
        </style>
      </head>
      <body>
        <h2>Hindi ASR Transcript</h2>
        <p>${text.replace(/\n/g, '<br>')}</p>
      </body>
    </html>
  `;
  const blob = new Blob(['\ufeff' + html], { type: 'application/msword' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = `transcript_${Date.now()}.doc`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}
